repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v1.7.0
        hooks:
        -   id: mypy
            verbose: true
            args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]
    -   repo: https://github.com/psf/black
        rev: 22.10.0
        hooks:
        -   id: black
